version: '3'
services:
  pgdb:
    restart: always
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: nietzsche1
      POSTGRES_DB: pulsepoint_db
    ports:
      - '5432:5432'
    expose:
      - '5432'
    volumes:
      - pg_data:/var/lib/postgresql/data
  web:
    restart: always
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    container_name: django
    volumes:
      - .:/pulsepoint
      - ./entrypoint.sh:/usr/pulsepoint/entrypoint.sh  # Add this line
    ports:
      - '8000:8000'
    depends_on:
      - pgdb

volumes:
  pg_data: