# Generated by Django 4.2.1 on 2023-12-24 23:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
        ('accounts', '0003_useractivation'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gender', models.CharField(max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('contact_address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('phone', models.CharField(default='', max_length=12)),
                ('zip_code', models.CharField(default='', max_length=10)),
                ('local_government', models.CharField(default='', max_length=25)),
                ('state', models.CharField(max_length=255)),
                ('home_address', models.CharField(default='', max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100)),
                ('emergency_contact_relationship', models.CharField(blank=True, max_length=50)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DonorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_type', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5)),
                ('medical_conditions', models.TextField(blank=True)),
                ('total_donations', models.PositiveIntegerField(default=0)),
                ('last_donation_date', models.DateField(blank=True, null=True)),
                ('quantity_donated', models.FloatField(default=0)),
                ('eligibility_status', models.CharField(choices=[('Eligible', 'Eligible'), ('Deferred', 'Deferred'), ('Restricted', 'Restricted')], default='Eligible', max_length=20)),
                ('eligibility_reason', models.TextField(blank=True)),
                ('preferred_times', models.TextField(blank=True)),
                ('receive_notifications', models.BooleanField(default=True)),
                ('opt_in_communication', models.BooleanField(default=True)),
                ('consent_share_information', models.BooleanField(default=False)),
                ('terms_and_conditions_acknowledged', models.BooleanField(default=False)),
                ('additional_notes', models.TextField(blank=True)),
                ('preferred_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='donations.donationcenter')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile')),
            ],
        ),
    ]
