# Generated by Django 4.2.1 on 2023-12-26 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_donorprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DonorProfile',
        ),
    ]
