# Generated by Django 4.2.1 on 2023-12-26 20:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_delete_donorprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('donation_date_time', models.DateTimeField()),
                ('blood_type', models.CharField(max_length=5)),
                ('donation_quantity', models.PositiveIntegerField()),
                ('health_assessment', models.TextField(blank=True, null=True)),
                ('processing_status', models.CharField(blank=True, max_length=255, null=True)),
                ('storage_information', models.TextField(blank=True, null=True)),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('is_scheduled_donation', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InvestigationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile'),
        ),
        migrations.CreateModel(
            name='LaboratoryInvestigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('result', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='donations.investigationtype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.userprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DonorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_type', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5)),
                ('medical_conditions', models.TextField(blank=True)),
                ('total_donations', models.PositiveIntegerField(default=0)),
                ('last_donation_date', models.DateField(blank=True, null=True)),
                ('quantity_donated', models.FloatField(default=0)),
                ('eligibility_status', models.CharField(choices=[('Eligible', 'Eligible'), ('Deferred', 'Deferred'), ('Restricted', 'Restricted')], default='Eligible', max_length=20)),
                ('eligibility_reason', models.TextField(blank=True)),
                ('preferred_times', models.TextField(blank=True)),
                ('receive_notifications', models.BooleanField(default=True)),
                ('opt_in_communication', models.BooleanField(default=True)),
                ('consent_share_information', models.BooleanField(default=False)),
                ('terms_and_conditions_acknowledged', models.BooleanField(default=False)),
                ('additional_notes', models.TextField(blank=True)),
                ('preferred_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='donations.donationcenter')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='DonationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('volunteer_assignment_status', models.BooleanField(default=False)),
                ('scheduled_date_time', models.DateTimeField()),
                ('appointment_status', models.CharField(max_length=50)),
                ('reminder_settings', models.CharField(blank=True, max_length=50, null=True)),
                ('health_assessment', models.TextField(blank=True, null=True)),
                ('notification_preferences', models.CharField(blank=True, max_length=50, null=True)),
                ('additional_notes', models.TextField(blank=True)),
                ('assigned_volunteer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='donations.volunteer')),
                ('blood_donation', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='donations.blooddonation')),
                ('donation_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donations.donationcenter')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='blooddonation',
            name='assigned_volunteer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='donations.volunteer'),
        ),
        migrations.AddField(
            model_name='blooddonation',
            name='donation_center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donations.donationcenter'),
        ),
        migrations.AddField(
            model_name='blooddonation',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile'),
        ),
        migrations.AddField(
            model_name='blooddonation',
            name='laboratory_investigations',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='donations.laboratoryinvestigation'),
        ),
    ]
