# Generated by Django 4.2.1 on 2023-12-27 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_delete_donorprofile'),
        ('donations', '0002_blooddonation_investigationtype_alter_volunteer_user_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BloodDonation',
            new_name='BloodDonationLog',
        ),
    ]
