# Generated by Django 4.2.1 on 2023-12-27 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0003_rename_blooddonation_blooddonationlog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donationschedule',
            old_name='blood_donation',
            new_name='blood_donation_log',
        ),
    ]
