# Generated by Django 4.2.1 on 2023-12-27 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0004_rename_blood_donation_donationschedule_blood_donation_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationschedule',
            name='appointment_status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
