# Generated by Django 4.2.1 on 2023-12-27 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0005_alter_donationschedule_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blooddonationlog',
            name='donation_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blooddonationlog',
            name='donation_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
